### ISSUE TITLE
Setting the "Preferred" quality definition isn't being applied

### ISSUE THREAD

**Issue by ChadTaljaardt** [buildarr/buildarr-radarr#46]
Hello, 

In my yml configuration I have the following: 

```yml
WEBRip-1080p:
  title: null
  min: 0.0
  preferred: 95.0
  max: 100.0
```

You can see the values are set correctly here: 

<img width="1248" alt="Screenshot 2024-02-02 at 1 30 21 PM" src="https://github.com/buildarr/buildarr-radarr/assets/13891249/4a7cb325-fc7f-47db-884f-4f41e0e81b94">

But If I change the values of the yaml and then re-run the sync it updates the `min` and `max` but not the `preferred`

```yml
WEBRip-1080p:
  title: null
  min: 10.0
  preferred: 150.0
  max: 300.0
```

<img width="1249" alt="Screenshot 2024-02-02 at 1 32 39 PM" src="https://github.com/buildarr/buildarr-radarr/assets/13891249/32ef2a76-325c-40ab-aa48-477586cf9250">
