### ISSUE TITLE
ColonReplacementFormat error

### ISSUE THREAD

**Issue by physk** [buildarr/buildarr-radarr#67]
Error
```shell
buildarr-1        | 2024-12-29 14:51:11,184 buildarr:1 buildarr.cli.run [INFO] <radarr> (radarr-hd) Finished fetching instance secrets
buildarr-1        | 2024-12-29 14:51:11,184 buildarr:1 buildarr.cli.run [INFO] <radarr> (radarr-hd) Running connection test
buildarr-1        | 2024-12-29 14:51:11,184 buildarr:1 buildarr.cli.run [INFO] <radarr> (radarr-hd) Connection test successful
buildarr-1        | 2024-12-29 14:51:11,184 buildarr:1 buildarr.cli.run [INFO] Performing post-initialisation configuration render
buildarr-1        | 2024-12-29 14:51:11,275 buildarr:1 buildarr.cli.run [INFO] Finished performing post-initialisation configuration render
buildarr-1        | 2024-12-29 14:51:11,276 buildarr:1 buildarr.cli.run [INFO] Updating configuration on remote instances
buildarr-1        | 2024-12-29 14:51:11,276 buildarr:1 buildarr.cli.run [INFO] <radarr> (radarr-hd) Fetching remote configuration to check if updates are required
buildarr-1        | 2024-12-29 14:51:11,290 buildarr:1 buildarr.cli.daemon [ERROR] <radarr> (radarr-hd) An error occurred while applying initial configuration: 1 validation error for NamingConfigResource
buildarr-1        | colonReplacementFormat
buildarr-1        |   value is not a valid enumeration member; permitted: 'delete', 'dash', 'spaceDash', 'spaceDashSpace' (type=type_error.enum; enum_values=[<ColonReplacementFormat.DELETE: 'delete'>, <ColonReplacementFormat.DASH: 'dash'>, <ColonReplacementFormat.SPACEDASH: 'spaceDash'>, <ColonReplacementFormat.SPACEDASHSPACE: 'spaceDashSpace'>])
buildarr-1        | Traceback (most recent call last):
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
buildarr-1        |     run_apply()
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 235, in _run
buildarr-1        |     remote_instance_config = manager.from_remote(instance_config, instance_secrets)
buildarr-1        |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
buildarr-1        |     return instance_config.from_remote(secrets)
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/__init__.py", line 193, in from_remote
buildarr-1        |     settings=RadarrSettings.from_remote(secrets),
buildarr-1        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
buildarr-1        |     fields[field_name] = field.type_.from_remote(secrets)
buildarr-1        |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/settings/media_management.py", line 432, in from_remote
buildarr-1        |     api_naming_config = radarr.NamingConfigApi(api_client).get_naming_config()
buildarr-1        |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
buildarr-1        |   File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
buildarr-1        |   File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api/naming_config_api.py", line 72, in get_naming_config
buildarr-1        |     return self.get_naming_config_with_http_info(**kwargs)  # noqa: E501
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
buildarr-1        |   File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
buildarr-1        |   File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api/naming_config_api.py", line 163, in get_naming_config_with_http_info
buildarr-1        |     return self.api_client.call_api(
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 413, in call_api
buildarr-1        |     return self.__call_api(resource_path, method,
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 254, in __call_api
buildarr-1        |     return_data = self.deserialize(response_data, response_type)
buildarr-1        |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 324, in deserialize
buildarr-1        |     return self.__deserialize(data, response_type)
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 363, in __deserialize
buildarr-1        |     return self.__deserialize_model(data, klass)
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 755, in __deserialize_model
buildarr-1        |     return klass.from_dict(data)
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "/usr/local/lib/python3.11/site-packages/radarr/models/naming_config_resource.py", line 96, in from_dict
buildarr-1        |     _obj = NamingConfigResource.parse_obj({
buildarr-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr-1        |   File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
buildarr-1        |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
buildarr-1        | pydantic.error_wrappers.ValidationError: 1 validation error for NamingConfigResource
buildarr-1        | colonReplacementFormat
buildarr-1        |   value is not a valid enumeration member; permitted: 'delete', 'dash', 'spaceDash', 'spaceDashSpace' (type=type_error.enum; enum_values=[<ColonReplacementFormat.DELETE: 'delete'>, <ColonReplacementFormat.DASH: 'dash'>, <ColonReplacementFormat.SPACEDASH: 'spaceDash'>, <ColonReplacementFormat.SPACEDASHSPACE: 'spaceDashSpace'>])
buildarr-1        | 2024-12-29 14:51:11,291 buildarr:1 buildarr.cli.daemon [WARNING] Aborted applying initial configuration
buildarr-1        | 2024-12-29 14:51:11,292 buildarr:1 buildarr.cli.daemon [INFO] Finished reloading config
```

```yaml
radarr:
  port: 443
  protocol: "https"
  # api_key: redacted
  settings:
    general:
      security:
        authentication: external
        # authentication: form
        # authentication_required: local-disabled
        # username: physk
        # password: redacted
        # certificate_validation: enabled
    media_management:
      rename_movies: true
      replace_illegal_characters: true
      colon_replacement: delete
      standard_movie_format: '{Movie Title} ({Release Year}) {Quality Full}'
      movie_folder_format: '{Movie Title} ({Release Year})'
      create_missing_movie_folders: true
      delete_empty_folders: false
      skip_free_space_check: false
      minimum_free_space: 100
      use_hardlinks: true
      import_extra_files: false
      unmonitor_deleted_movies: false
      propers_and_repacks: do-not-prefer
      analyze_video_files: true
      rescan_folder_after_refresh: always
      recycling_bin: null
      recycling_bin_cleanup: 7
  instances:
    radarr-hd:
      hostname: "hd.radarr.redacted"
      port: 443
      protocol: "https"
      settings:
        general:
          host:
            instance_name: Radarr (HD)
          root_folders:
            delete_unmanaged: true
            definitions:
              - /media/Movies/adult/hd
```

I've also tried with the media_management under the instance. and without the colon_replacement all together and it still comes up, also tried 'replace' etc

this is a new instance of Radarr - Version 5.16.3.9541
